namespace ContactManagerApp.Models
{
    public class Category
    {
        // will be generated by DB
        public int CategoryId { get; set; }
        public string Name { get; set; } = string.Empty;
    }
}
